gralloc: Drop libcxx
Isn't even needed and causes errors like this:
bionic/libc/include/sys/types.h:48:9: error: unknown type name 'uint32_t'
   48 | typedef uint32_t __id_t;
      |         ^
bionic/libc/include/sys/types.h:72:9: error: unknown type name 'uint64_t'
   72 | typedef uint64_t ino64_t;
      |         ^
bionic/libc/include/sys/types.h:74:9: error: unknown type name 'uint32_t'
   74 | typedef uint32_t __nlink_t;
      |         ^
bionic/libc/include/sys/types.h:84:9: error: unknown type name 'uint32_t'
   84 | typedef uint32_t __useconds_t;
      |         ^
bionic/libc/include/sys/types.h:89:9: error: unknown type name 'uint32_t'
   89 | typedef uint32_t dev_t;
      |         ^
bionic/libc/include/sys/types.h:112:9: error: unknown type name 'int32_t'
  112 | typedef int32_t __socklen_t;
      |         ^
bionic/libc/include/sys/types.h:140:9: error: unknown type name 'uint32_t'; did you mean 'uint_t'?
  140 | typedef uint32_t u_int32_t;
      |         ^
bionic/libc/include/sys/types.h:131:29: note: 'uint_t' declared here
  131 | typedef unsigned int        uint_t;
      |                             ^
bionic/libc/include/sys/types.h:141:9: error: unknown type name 'uint16_t'; did you mean 'uint_t'?
  141 | typedef uint16_t u_int16_t;
      |         ^
bionic/libc/include/sys/types.h:131:29: note: 'uint_t' declared here
  131 | typedef unsigned int        uint_t;
      |                             ^
bionic/libc/include/sys/types.h:142:9: error: unknown type name 'uint8_t'; did you mean 'uint_t'?
  142 | typedef uint8_t  u_int8_t;
      |         ^
bionic/libc/include/sys/types.h:131:29: note: 'uint_t' declared here
  131 | typedef unsigned int        uint_t;